server:
  image:
    repository: jetbrains/teamcity-server
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 8111
  ingress:
    enabled: true
    className: traefik
    host: teamcity.pawhelp.internal
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: teamcity-teamcity-vpn-only@kubernetescrd
      cert-manager.io/cluster-issuer: pawhelp-selfsigned
    tls:
      enabled: true
      secretName: teamcity-internal-tls
  internalAccess:
    enabled: true
    allowedCIDRs:
      - 10.44.0.0/24
      - 10.45.0.0/24
  persistence:
    dataSize: 20Gi
    logsSize: 5Gi
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 3Gi

agent:
  enabled: true
  replicas: 1
  image:
    repository: jetbrains/teamcity-agent
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 2Gi
