image:
  repository: postgres
  tag: "16"
  pullPolicy: IfNotPresent

auth:
  database: pawhelp
  username: pawhelp
  password: pawhelp_password

persistence:
  size: 8Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi


backup:
  enabled: true
  schedule: "0 2 * * *"
  retentionDays: 7
  storageSize: 8Gi
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi