{{- if .Values.clusterSecretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
spec:
  provider:
    aws:
      service: {{ .Values.clusterSecretStore.service }}
      region: {{ .Values.clusterSecretStore.region }}
{{- end }}
{{- if .Values.vaultSecretStore.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.vaultSecretStore.name }}
spec:
  provider:
    vault:
      server: {{ .Values.vaultSecretStore.server | quote }}
      path: {{ .Values.vaultSecretStore.path | quote }}
      version: {{ .Values.vaultSecretStore.version | quote }}
      auth:
        tokenSecretRef:
          name: {{ .Values.vaultSecretStore.tokenSecretRef.name }}
          key: {{ .Values.vaultSecretStore.tokenSecretRef.key }}
          namespace: {{ .Values.vaultSecretStore.tokenSecretRef.namespace }}
{{- end }}