{{- if .Values.clusterSecretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
spec:
  provider:
    aws:
      service: {{ .Values.clusterSecretStore.service }}
      region: {{ .Values.clusterSecretStore.region }}
{{- end }}
