{{- if and .Values.backup.enabled .Values.backup.s3.enabled .Values.backup.s3.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-postgres-backup-s3
  labels:
    app.kubernetes.io/name: pawhelp-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  refreshInterval: {{ .Values.backup.s3.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .Values.backup.s3.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.backup.s3.externalSecret.secretStoreRef.name }}
  target:
    name: {{ .Release.Name }}-postgres-backup-s3
    creationPolicy: Owner
  data:
    {{- range .Values.backup.s3.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key | quote }}
    {{- end }}
{{- end }}
