apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "crm-manager.fullname" . }}-data
  labels:
    {{- include "crm-manager.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}