apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crm-manager-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: pawhelp
  source:
    repoURL: https://github.com/Osavazya/PawHelp-infra.git
    targetRevision: master
    path: helm/crm-manager
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: crm-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true