apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pawhelp-prod-root
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  project: pawhelp
  source:
    repoURL: https://github.com/Osavazya/PawHelp-infra.git
    targetRevision: prod
    path: argocd/environments/prod
    directory:
      recurse: false
      include: '*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true