apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teamcity
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: pawhelp
  source:
    repoURL: https://github.com/Osavazya/PawHelp-infra.git
    targetRevision: master
    path: helm/teamcity
  destination:
    server: https://kubernetes.default.svc
    namespace: teamcity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

