apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pawhelp-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: pawhelp
  source:
    repoURL: https://github.com/Osavazya/PawHelp-infra.git
    targetRevision: main
    path: infra/helm/pawhelp
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pawhelp-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

