apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-teamcity-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: teamcity-server
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: teamcity-server
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8111
          volumeMounts:
            - name: data
              mountPath: /data/teamcity_server/datadir
            - name: logs
              mountPath: /opt/teamcity/logs
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-teamcity-data
        - name: logs
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-teamcity-logs

