{{- if .Values.server.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-teamcity-server
spec:
  ingressClassName: {{ .Values.server.ingress.className }}
  rules:
    - host: {{ .Values.server.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-teamcity-server
                port:
                  name: http
{{- end }}

