apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pawhelp-backend.fullname" . }}-uploads
  labels:
    {{- include "pawhelp-backend.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.uploads.size }}

