cert-manager:
  installCRDs: true
  replicaCount: 1
  nodeSelector:
    pawhelp.io/node-pool: infra
  tolerations:
    - key: pawhelp.io/node-pool
      operator: Equal
      value: infra
      effect: NoSchedule
  webhook:
    nodeSelector:
      pawhelp.io/node-pool: infra
    tolerations:
      - key: pawhelp.io/node-pool
        operator: Equal
        value: infra
        effect: NoSchedule
  cainjector:
    nodeSelector:
      pawhelp.io/node-pool: infra
    tolerations:
      - key: pawhelp.io/node-pool
        operator: Equal
        value: infra
        effect: NoSchedule
  startupapicheck:
    nodeSelector:
      pawhelp.io/node-pool: infra
    tolerations:
      - key: pawhelp.io/node-pool
        operator: Equal
        value: infra
        effect: NoSchedule
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 384Mi

external-secrets:
  installCRDs: true
  replicaCount: 1
  nodeSelector:
    pawhelp.io/node-pool: infra
  tolerations:
    - key: pawhelp.io/node-pool
      operator: Equal
      value: infra
      effect: NoSchedule
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 384Mi
  webhook:
    nodeSelector:
      pawhelp.io/node-pool: infra
    tolerations:
      - key: pawhelp.io/node-pool
        operator: Equal
        value: infra
        effect: NoSchedule
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
  certController:
    nodeSelector:
      pawhelp.io/node-pool: infra
    tolerations:
      - key: pawhelp.io/node-pool
        operator: Equal
        value: infra
        effect: NoSchedule
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

clusterSecretStore:
  enabled: true
  name: aws-parameter-store
  region: eu-central-1
  service: ParameterStore

clusterIssuer:
  enabled: true
  name: pawhelp-selfsigned
  type: selfSigned
