cert-manager:
  installCRDs: true
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 384Mi

external-secrets:
  installCRDs: true
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 384Mi
  webhook:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
  certController:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

clusterSecretStore:
  enabled: true
  name: aws-parameter-store
  region: eu-central-1
  service: ParameterStore

clusterIssuer:
  enabled: true
  name: pawhelp-selfsigned
  type: selfSigned
