all:
  vars:
    ansible_user: ec2-user
    k3s_version: stable
  children:
    control_plane:
      hosts:
        master-1:
          ansible_host: 203.0.113.10
    workers:
      hosts:
        worker-1:
          ansible_host: 203.0.113.11
        worker-2:
          ansible_host: 203.0.113.12

